### ISSUE TITLE
ISSUES IN Price-predictor.py

### ISSUE THREAD

**Issue by anshumangahlot** [AnubhabR/Stock-price-predictor#1]
### ISSUES: Model Not Printing Results

**Description**: The stock price prediction model does not print the predicted results after training and testing.
**Steps to Reproduce**:
	1.	Run the stock price prediction script.
	2.	After the model finishes training, check the console output.
	3.	The predicted stock prices are not displayed.
**Expected Behavior**: The script should print the predicted stock prices after training the model.
**Possible Causes**:
	•	The print statement is missing in the prediction section.
	•	The predicted results might not be returned or printed after the model prediction.
**Suggested Fix**:
	•	Ensure that model.predict() is followed by a print statement like print(predictions) to display the results.
	•	Verify the prediction variable is correctly populated with the predicted stock prices.

**Comment by AnubhabR** [comment]
Thanks for the report
